name: GitHub-Profile-Summary-Cards

on:
  schedule:
    - cron: "0 0 * * *" 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-summary-cards
    steps:
      - uses: actions/checkout@v2
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        with:
          USERNAME: LoKiiZoshi
          BRANCH_NAME: main
          UTC_OFFSET: "5:45"
